[general]
import = [ "themes/tokyonight_night.toml" ]

[terminal]
shell = "fish"

[font]
size = 14

[cursor.style]
blinking = "On"

[keyboard]
bindings = [
    { key = "Plus", mods = "Control", action = "IncreaseFontsize" },
    { key = "Plus", mods = "Control", action = "IncreaseFontsize" },
    { key = "Plus", mods = "Control", action = "IncreaseFontsize" },
    { key = "Plus", mods = "Control", action = "IncreaseFontsize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontsize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontsize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontsize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontsize" },
    { key = "S", mods = "Control|Shift", action = "PasteSelection" },
]
