fish_color_autosuggestion brblack --italic --theme=richer
fish_color_cancel -r --theme=richer
fish_color_command normal --bold --theme=richer
fish_color_comment red --theme=richer
fish_color_cwd cyan --theme=richer
fish_color_cwd_root cyan --theme=richer
fish_color_end green --theme=richer
fish_color_error brred --theme=richer
fish_color_escape brcyan --theme=richer
fish_color_history_current --bold --theme=richer
fish_color_host normal --theme=richer
fish_color_host_remote yellow --theme=richer
fish_color_normal normal --theme=richer
fish_color_operator brcyan --theme=richer
fish_color_param cyan --theme=richer
fish_color_quote yellow --theme=richer
fish_color_redirection cyan --bold --theme=richer
fish_color_search_match white --background=brblack --bold --theme=richer
fish_color_selection white --background=brblack --bold --theme=richer
fish_color_status red --theme=richer
fish_color_user brgreen --theme=richer
fish_color_valid_path --underline --theme=richer
fish_pager_color_description yellow --italics --theme=richer
fish_pager_color_prefix normal --bold --underline --theme=richer
fish_pager_color_progress brblack --italic --theme=richer
fish_pager_color_selected_background -r --theme=richer
