disableStartupPopups: true
os:
  editPreset: "nvim"
gui:
  nerdFontsVersion: "3"
  showBottomLine: false
  showRandomTip: false
  spinner:
    rate: 80
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
  theme:
    activeBorderColor:
      - "#5aaacc"
      - "bold"
    inactiveBorderColor:
      - "#716c90"
    selectedLineBgColor:
      - "#2d4356"
    defaultFgColor:
      - "#cdcae4"
