[colors]
# Regular colors
background = '#1F1F28'
black = '#16161D'
blue = '#7E9CD8'
cursor = '#DCD7BA'
cyan = '#6A9589'
foreground = '#DCD7BA'
green = '#76946A'
magenta = '#7B5EA7'
red = '#C34043'
white = '#C8C093'
yellow = '#C0A26E'

# UI colors
tabs = '#54546D'
tabs-active = '#FF9E3B'
selection-foreground = '#C8C093'
selection-background = '#2D4F67'

# Dim colors
# dim-black = '#asdasa'
# dim-blue = '#0E91B7'
# dim-cyan = '#93D4E7'
# dim-foreground = '#ECDC8A'
# dim-green = '#098749'
# dim-magenta = '#624A87'
# dim-red = '#C7102A'
# dim-white = '#C1C1C1'
# dim-yellow = '#E6A003'

# Light colors
light-black = '#727169'
light-blue = '#7FB4CA'
light-cyan = '#7AA89F'
light-foreground = '#DCD7BA'
light-green = '#98BB6C'
light-magenta = '#938AA9'
light-red = '#E82424'
light-white = '#DCD7BA'
light-yellow = '#E6C384'

