# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$shell\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$python\
$nix_shell\
$cmd_duration\
$line_break\
$jobs\
$status\
$container\
$character"""

[shell]
disabled = false
fish_indicator = '󰈺 fish'
bash_indicator = ' bash'
zsh_indicator = '󰏰 zsh'
powershell_indicator = '󰨊 pwsh'
nu_indicator = '󰞷 nu'

[directory]
format = '[ $path]($style)[$read_only]($read_only_style) '
read_only = ' 󰌾'
truncation_length = 0

[git_commit]
tag_disabled = false
tag_symbol = '  '

[python]
format = '[\($virtualenv\)]($style) '
style = 'bold bright-green'
detect_extensions = []
detect_files = []

[nix_shell]
symbol='❄ '

[fill]
symbol = '─'
style = 'bright-black'

[status]
disabled = false
format = '[$status]($style) '
style = 'bold bright-red'

[character]
success_symbol = '❯'
error_symbol = '[❯](bright-red)'
vimcmd_symbol = '❮'
