# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$jobs\
$line_break\
$status\
$character"""

[character]
success_symbol = '❱'
error_symbol = '[❱](bright-red)'

[directory]
read_only = ' 󰌾'
truncation_length = 0

[git_commit]
tag_disabled = false
tag_symbol = '  '

[status]
disabled = false
format = '[$status]($style) '
style = 'bold bright-red'
