# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$jobs\
$line_break\
$status\
$character"""

[directory]
format = "[ $path]($style)[$read_only]($read_only_style) "
read_only = ' 󰌾'
truncation_length = 0

[git_commit]
tag_disabled = false
tag_symbol = '  '

[status]
disabled = false
format = '[$status]($style) '
style = 'bold bright-red'

[character]
# success_symbol = '❱'
# error_symbol = '[❱](bright-red)'
success_symbol = '[>](bold)'
error_symbol = '[>](bright-red bold)'
