# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$conda\
$cmd_duration\
$line_break\
$jobs\
$character"""

[conda]
symbol = ''
format = '[\($environment\)]($style) '

[directory]
read_only = ' 󰌾'
truncation_length = 0

[git_status]
windows_starship = '/mnt/c/Program Files/starship/bin/starship.exe'
