#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b
nitrogen --restore
polybar &
nm-applet &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap           6

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
