disableStartupPopups: true
os:
  editPreset: 'nvim'
gui:
  nerdFontsVersion: "3"
  border: single
  showBottomLine: false
  spinner:
    rate: 80
    frames:
    - "⠋"
    - "⠙"
    - "⠹"
    - "⠸"
    - "⠼"
    - "⠴"
    - "⠦"
    - "⠧"
    - "⠇"
    - "⠏"
  theme:
    activeBorderColor:
    - "#ff966c"
    - "bold"
    inactiveBorderColor:
    - "#589ed7"
    searchingActiveBorderColor:
    - "#ff966c"
    - "bold"
    selectedLineBgColor:
    - "#2d3f76"
git:
  paging:
    useConfig: true
