disableStartupPopups: true
os:
  editPreset: "nvim"
gui:
  nerdFontsVersion: "3"
  showBottomLine: false
  showRandomTip: false
  spinner:
    rate: 80
    frames:
    - "⠋"
    - "⠙"
    - "⠹"
    - "⠸"
    - "⠼"
    - "⠴"
    - "⠦"
    - "⠧"
    - "⠇"
    - "⠏"
