[colors]
foreground=d1cfe9
background=191724

## Normal/regular colors (color palette 0-7)
regular0=191724
regular1=eb6f92
regular2=94c68d
regular3=f6c177
regular4=3a94b7
regular5=c4a7e7
regular6=9ccfd8
regular7=928eb4

## Bright colors (color palette 8-15)
bright0=585476
bright1=ff82a4
bright2=a7daa0
bright3=ffd58a
bright4=4fa7ca
bright5=d7bafb
bright6=afe3ec
bright7=d1cfe9

## Selection colors
selection-background=312D47

## Cursor colors
cursor=191724 d1cfe9

## URL colors
urls=c4a7e7
