[manager]
prepend_keymap = [
    { on = [
        "g",
        "d",
    ], run = "cd ~/Descargas", desc = "Go to the downloads directory" },
]

append_keymap = [
    { on = [
        "<C-n>",
    ], run = '''shell 'dragon-drop -x "$@"' --confirm''' },
    { on = [
        "?",
    ], run = "help" },
    { on = [
        "T",
    ], run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
]
