# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
"""

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
read_only = ' 󰌾'
truncation_length = 0
truncate_to_repo = false

[git_commit]
tag_disabled = false
tag_symbol = '  '
