[manager]
show_hidden = true
sort_by = "natural"

[preview]
tab_size   = 2
max_width  = 1000
max_height = 1000

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %*",   block = true, for = "windows" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
	{ run = 'mpv.exe %*', orphan = true, for = "windows" }
]
open = [
    { run = 'xdg-open "$@"', orphan = true, desc = "Open", for ="linux" },
    { run = "start %*", orphan = true, desc = "Open", for ="windows" }
]
