[manager]
show_hidden = true
sort_by = "natural"
sort_translit = false

[preview]
tab_size = 4
max_width = 1000
max_height = 1000

[opener]
open = [
	{ run = 'xdg-open "$1"', orphan = true, desc = "Open", for = "linux" },
	{ run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
