[colors]
foreground = "#c8d3f5"
background = "#222436"
cursor_bg = "#c8d3f5"
cursor_border = "#c8d3f5"
cursor_fg = "#222436"
selection_bg = "#2d3f76"
selection_fg = "#c8d3f5"
split = "#82aaff"
compose_cursor = "#ff966c"
scrollbar_thumb = "#2f334d"

ansi = ["#1b1d2b", "#ff757f", "#c3e88d", "#ffc777", "#82aaff", "#c099ff", "#86e1fc", "#828bb8"]
brights = ["#444a73", "#ff8d94", "#c7fb6d", "#ffd8ab", "#9ab8ff", "#caabff", "#b2ebff", "#c8d3f5"]

[colors.tab_bar]
background = "#222436"

[colors.tab_bar.active_tab]
fg_color = "#c8d3f5"
bg_color = "#394b70"
italic = true
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#2f334d"
fg_color = "#828bb8"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#2f334d"
fg_color = "#828bb8"
italic = true

[metadata]
aliases = []
author = "warbacon"
name = "tokyonight_moon"
