---
- hosts: localhost

  tasks:
    - name: Install Hyprland packages
      become: true
      community.general.pacman:
        name:
          - brightnessctl
          - dunst
          - grim
          - hypridle
          - hyprland
          - hyprlock
          - hyprpaper
          - kitty
          - libcanberra
          - libnotify
          - pulsemixer
          - rofi-wayland
          - rofimoji
          - slurp
          - waybar
          - wl-clip-persist
          - wtype
          - xdg-desktop-portal-gtk
          - xdg-desktop-portal-hyprland
          - xdg-user-dirs
          - yazi

    - name: Install Hyprland aur packages
      kewlfft.aur.aur:
        name:
          - hyprsunset
          - uwsm

    - name: Create home folder folders
      ansible.builtin.command: xdg-user-dirs-update

    - name: Clone dotfiles
      git:
        repo: https://github.com/warbacon/dotfiles
        dest: /tmp/dotfiles

    - name: Apply hypr config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/hypr"

    - name: Apply waybar config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/waybar"

    - name: Apply dunst config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/dunst"

    - name: Apply rofi config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/rofi"

    - name: Hide GTK titlebar buttons
      ansible.builtin.command: gsettings set org.gnome.desktop.wm.preferences button-layout ''
